/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AL-AMIN
 */
public class Delete extends javax.swing.JFrame {

    
    Connection conn=null;
   ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
         conn=sqlConnection.dbConnector();
         show_user();
    }

    private void show_user(){
        
        try{ 
        
        String sql = "select * from data_table";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        Delete_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        blood_group = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Blood_group = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Delete_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 0));
        jButton2.setText("Delete");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 100, 40));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 255, 0));
        id.setText("Id");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, 20));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 0));
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 30));

        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city.setForeground(new java.awt.Color(204, 255, 0));
        city.setText("City");
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 50, 30));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 0));
        phone.setText("Phone");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 0));
        email.setText("Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 50, 30));

        blood_group.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group.setForeground(new java.awt.Color(255, 255, 0));
        blood_group.setText("Blood group");
        getContentPane().add(blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 30));

        Id.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 160, 30));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, 30));

        City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 140, 30));

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 30));
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, 30));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 0));
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, 50));

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 120, 40));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 51, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Student Management System");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 430, 60));

        Blood_group.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 30));

        Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, 30));

        Delete_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "City", "Phone", "Email", "Blood group", "Gender"
            }
        ));
        Delete_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Delete_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 730, 350));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AL-AMIN\\Desktop\\ss.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-60, 0, 1140, 600);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1080, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Admin().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String sql="delete from data_table where Id=?";

        try{
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, Id.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Deleted Successfully");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        show_user();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void Delete_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_tableMouseClicked
        // TODO add your handling code here:

        int i = Delete_table.getSelectedRow();
        TableModel model = Delete_table.getModel();
        Id.setText(model.getValueAt(i, 0).toString());
        Name.setText(model.getValueAt(i, 1).toString());
        City.setText(model.getValueAt(i, 2).toString());
        Phone.setText(model.getValueAt(i, 3).toString());
        Email.setText(model.getValueAt(i, 4).toString());
        Blood_group.setText(model.getValueAt(i, 5).toString());
        Gender.setText(model.getValueAt(i, 6).toString());

    }//GEN-LAST:event_Delete_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blood_group;
    private javax.swing.JTextField City;
    private javax.swing.JTable Delete_table;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JLabel blood_group;
    private javax.swing.JLabel city;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    // End of variables declaration//GEN-END:variables
}
