/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AL-AMIN
 */
public class Search extends javax.swing.JFrame {
  
    Connection conn=null;
   ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    public Search() {
        initComponents();
         conn=sqlConnection.dbConnector();
      show_user();
    }

    
    private void show_user(){
        
        try{ 
        
        String sql = "select * from data_table";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        Search_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_Box = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Search_table = new javax.swing.JTable();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        blood_group = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Blood_group = new javax.swing.JTextField();
        Student_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search_Box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Search_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BoxActionPerformed(evt);
            }
        });
        Search_Box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_BoxKeyReleased(evt);
            }
        });
        getContentPane().add(Search_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 260, 40));

        Search.setBackground(new java.awt.Color(51, 153, 255));
        Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 110, 40));

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 120, 40));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Student Management System");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 430, 60));

        Search_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "City", "Phone", "Email", "Blood group", "Gender"
            }
        ));
        Search_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Search_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 630, 380));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 0));
        id.setText("Id");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, 30));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 0));
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 0));
        city.setText("City");
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 80, 30));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 0));
        phone.setText("Phone");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 0));
        email.setText("Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 80, 30));

        blood_group.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group.setForeground(new java.awt.Color(255, 255, 0));
        blood_group.setText("Blood group");
        getContentPane().add(blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 120, 30));

        Id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, 30));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 30));

        City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 210, 30));

        Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 200, 30));
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 210, 30));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 0));
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 120, 50));

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 210, 30));

        Blood_group.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 210, 30));

        Student_L.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Student_L.setForeground(new java.awt.Color(255, 51, 102));
        Student_L.setText("Please search by Name or id");
        getContentPane().add(Student_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AL-AMIN\\Desktop\\ss.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
        try{
            
            String sql="select * from data_table where  Id=? or Name =? or City=? or Phone=? or Email=? or Blood_group=? or Gender=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, Search_Box.getText());
             pst.setString(2, Search_Box.getText());
             pst.setString(3, Search_Box.getText());
             pst.setString(4, Search_Box.getText());
             pst.setString(5, Search_Box.getText());
             pst.setString(6, Search_Box.getText());
             pst.setString(7, Search_Box.getText());
             
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Id");
                Id.setText(add1);
                 String add2=rs.getString("Name");
                Name.setText(add2);
                 String add3=rs.getString("City");
                City.setText(add3);
                 String add4=rs.getString("Phone");
                Phone.setText(add4);
                 String add5=rs.getString("Email");
                Email.setText(add5);
                 String add6=rs.getString("Blood_group");
                Blood_group.setText(add6);
                 String add7=rs.getString("Gender");
                Gender.setText(add7);
            }
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
        finally{
            
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        
    }//GEN-LAST:event_SearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Admin().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Search_BoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_BoxKeyReleased
       
        /*
        try{
            
            String sql="select * from data_table where Id=? or Name =?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, Search_Box.getText());
             
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getNString("Id");
                Id.setText(add1);
                 String add2=rs.getNString("Name");
                Name.setText(add2);
                 String add3=rs.getNString("City");
                City.setText(add3);
                 String add4=rs.getNString("Phone");
                Phone.setText(add4);
                 String add5=rs.getNString("Email");
                Email.setText(add5);
                 String add6=rs.getNString("Blood_group");
                Blood_group.setText(add6);
                 String add7=rs.getNString("Gender");
                Gender.setText(add7);
            }
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
        */
    }//GEN-LAST:event_Search_BoxKeyReleased

    private void Search_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_tableMouseClicked
     int i = Search_table.getSelectedRow();
        TableModel model = Search_table.getModel();
        Id.setText(model.getValueAt(i, 0).toString());
        Name.setText(model.getValueAt(i, 1).toString());
        City.setText(model.getValueAt(i, 2).toString());
        Phone.setText(model.getValueAt(i, 3).toString());
        Email.setText(model.getValueAt(i, 4).toString());
         Blood_group.setText(model.getValueAt(i, 5).toString());
          Gender.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_Search_tableMouseClicked

    private void Search_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_BoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blood_group;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Search_Box;
    private javax.swing.JTable Search_table;
    private javax.swing.JLabel Student_L;
    private javax.swing.JLabel blood_group;
    private javax.swing.JLabel city;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    // End of variables declaration//GEN-END:variables
}
