/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms;

/**
 *
 * @author AL-AMIN
 *
 */
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class Update extends javax.swing.JFrame {

    Connection conn=null;
   ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
         conn=sqlConnection.dbConnector();
        show_user();

    }

    private void show_user(){
        
        try{ 
        
        String sql = "select * from data_table";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        Update_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Update_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        blood_group = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        Blood_group = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "City", "Phone", "Email", "Blood group", "Gender"
            }
        ));
        Update_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Update_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 730, 390));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 51));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 100, 40));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 0));
        id.setText("Id");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 40, 20));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(153, 153, 0));
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 30));

        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city.setForeground(new java.awt.Color(153, 153, 0));
        city.setText("City");
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 30));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(153, 153, 0));
        phone.setText("Phone");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 0));
        email.setText("Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 30));

        Id.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 40));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, 30));

        City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, 30));

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, 30));
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, 30));

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 120, 40));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 51, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Student Management System");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 430, 60));

        Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, 30));

        blood_group.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blood_group.setForeground(new java.awt.Color(204, 204, 0));
        blood_group.setText("Blood group");
        getContentPane().add(blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 120, 30));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(204, 204, 0));
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, 50));

        Blood_group.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AL-AMIN\\Desktop\\ss.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1092, 637);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Admin().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Update_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_tableMouseClicked
        // TODO add your handling code here:

        int i = Update_table.getSelectedRow();
        TableModel model = Update_table.getModel();
        Id.setText(model.getValueAt(i, 0).toString());
        Name.setText(model.getValueAt(i, 1).toString());
        City.setText(model.getValueAt(i, 2).toString());
        Phone.setText(model.getValueAt(i, 3).toString());
        Email.setText(model.getValueAt(i, 4).toString());
         Blood_group.setText(model.getValueAt(i, 5).toString());
          Gender.setText(model.getValueAt(i, 6).toString());
      

       


    }//GEN-LAST:event_Update_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{
            String value1=Id.getText();
            String value2=Name.getText();
            String value3=City.getText();
            String value4=Phone.getText();
            String value5=Email.getText();
            String value6=Blood_group.getText();
            String value7=Gender.getText();
            
            String sql= "update data_table set Name='"+value2+"', City='"+value3+"', "
                        + "Phone='"+value4+"',Email='"+value5+"',Blood_group='"+value6+"'"
                        + " ,Gender='"+value7+"' where Id='"+value1+"' ";

            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data updated");
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
        show_user();
        
        
       
        
         
      // String query="Update Data_table SET Name='"+Name.getText()+"', City='"+City.getText()+"', Phone='"+Phone.getText()+"',Email='"+Email.getText()+"'+ WHERE Id= "Id.getText()";
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blood_group;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTable Update_table;
    private javax.swing.JLabel blood_group;
    private javax.swing.JLabel city;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    // End of variables declaration//GEN-END:variables

    private void JComboBox(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
